name: hindawi
description: "Unofficial hindawi.org front-end"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.4.0

environment:
  sdk: ^3.8.0-70.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  html: ^0.15.5
  http: ^1.3.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"


flutter:

  uses-material-design: true

  assets:
    - assets/default.png




